language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.4
  - nightly

env:
  global:
    - PYTHON=''

after_success:
  - julia --project -e 'using Pkg; Pkg.add("Coverage"); import OscillatoryFlows; joinpath(dirname(pathof(OscillatoryFlows)), ".."); using Coverage; Coveralls.submit(Coveralls.process_folder());'
  - julia --project -e 'using Pkg; Pkg.add("Coverage"); import OscillatoryFlows; joinpath(dirname(pathof(OscillatoryFlows)), ".."); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - julia: nightly

notifications:
  email: true
  
